# This workflow is not intended for execution.
# It exists to help dependabot understand dependencies
name: dummy

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@67e9c72af6e0492df856527b474995862b7b6591 # v2.0.0
        with:
          workload_identity_provider: projects/912487971903/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider
          service_account: github-actions@shogo82148-7b957.iam.gserviceaccount.com

      - uses: shogo82148/actions-post-run@31b26ef20972dfeff5d6cea16d940cf6c36f7a2f # v1.0.0
        with:
          run: echo "hello, world"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm test
